/*
 * Railways API Game!
 * Find your way in the Tokyo railway system!
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package sdk.railways.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * Route
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-03-07T15:52:27.062333+01:00[Europe/Amsterdam]")
public class Route {
  @JsonProperty("stationsToSwitchTrain")
  private List<Integer> stationsToSwitchTrain = null;

  public Route stationsToSwitchTrain(List<Integer> stationsToSwitchTrain) {
    this.stationsToSwitchTrain = stationsToSwitchTrain;
    return this;
  }

  public Route addStationsToSwitchTrainItem(Integer stationsToSwitchTrainItem) {
    if (this.stationsToSwitchTrain == null) {
      this.stationsToSwitchTrain = new ArrayList<>();
    }
    this.stationsToSwitchTrain.add(stationsToSwitchTrainItem);
    return this;
  }

   /**
   * Get stationsToSwitchTrain
   * @return stationsToSwitchTrain
  **/
  @ApiModelProperty(value = "")
  public List<Integer> getStationsToSwitchTrain() {
    return stationsToSwitchTrain;
  }

  public void setStationsToSwitchTrain(List<Integer> stationsToSwitchTrain) {
    this.stationsToSwitchTrain = stationsToSwitchTrain;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Route route = (Route) o;
    return Objects.equals(this.stationsToSwitchTrain, route.stationsToSwitchTrain);
  }

  @Override
  public int hashCode() {
    return Objects.hash(stationsToSwitchTrain);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Route {\n");
    
    sb.append("    stationsToSwitchTrain: ").append(toIndentedString(stationsToSwitchTrain)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

