/*
 * Railways API Game!
 * Find your way in the Tokyo railway system!
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package sdk.railways.model;

import java.util.Objects;
import java.util.Arrays;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets SubmissionResult
 */
public enum SubmissionResult {
  
  CORRECT("CORRECT"),
  
  ROUTE_TOO_LONG("ROUTE_TOO_LONG"),
  
  INCORRECT_ORIGIN("INCORRECT_ORIGIN"),
  
  INCORRECT_DESTINATION("INCORRECT_DESTINATION");

  private String value;

  SubmissionResult(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static SubmissionResult fromValue(String text) {
    for (SubmissionResult b : SubmissionResult.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + text + "'");
  }
}

